# Generated by Django 4.2 on 2025-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_default_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
